### PR TITLE
fix: Prevent error during composer install by handling missing app_mo…

### LINKED ISSUE #10: Bug Report: Error during `composer install` due to missing `app/Modules` directory
When installing the Dust package using `composer require`, the installation fails during the `package:discover` step due to a missing `app/Modules` directory. The `app_modules()` function in `helpers.php` attempts to scan a directory that does not exist, resulting in a fatal error.

---

## Steps to Reproduce

1. Create a new Laravel 10 project.
2. Run the command to install the Dust package:
   ```bash
   composer require cyberbugz/dust
   ```
3. Observe the error during the `post-autoload-dump` phase.

---

## Expected Behavior

The installation should complete without errors, and the package should handle missing directories gracefully.

---

## Actual Behavior

The installation fails with the following error:

```plaintext
ErrorException

scandir(I:\---\---\---\Modules): The system cannot find the file specified (code: 2)

at vendor\cyberbugz\dust\src\Support\helpers.php:13
  9▕
 11▕     function app_modules(): array
 12▕     {
➜ 13▕         return array_filter(scandir(modules_path()), fn ($module) => ! in_array($module, ['.', '..']));
 14▕     }
 15▕ }
 16▕

1   vendor\cyberbugz\dust\src\Support\helpers.php:13
2   vendor\cyberbugz\dust\src\Providers\MigrationServiceProvider.php:30

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

---

## Environment

- **Dust Version**: v5.1.9
- **Laravel Version**: 10.48.25
- **PHP Version**: 8.1
- **OS**: Windows

### PR DESCRIPTION
**Pull request by herooiboo**
…dules directory

Closes #10

### CODE REVIEW

File: src/Support/helpers.php [hunk 1]
```diff
@@ -10,6 +10,12 @@ function modules_path(): string
 if (! function_exists('app_modules')) {
     function app_modules(): array
     {
+        $modulesPath = modules_path();
+
+        if (!is_dir($modulesPath)) {
+            return [];
+        }
+
         return array_filter(scandir(modules_path()), fn ($module) => ! in_array($module, ['.', '..']));
```
Comment (mansonxasthur) [inline src/Support/helpers.php]: replace `modules_path()` line `19` with `$modulePath`

**Review by mansonxasthur — CHANGES_REQUESTED** [review]

**Review by mansonxasthur — APPROVED** [review]
